Thmanyah.CMS/Controllers/CategoriesController.cs
using Application.Controllers;
using Application.Services.Contracts;
using Domain.Dtos;
using Microsoft.AspNetCore.Mvc;

namespace Thmanyah.CMS.Controllers;

public class CategoriesController : BaseAdminController
{
    private readonly IPostCategoryService _service;
    public CategoriesController(IPostCategoryService service) => _service = service;
    [HttpGet]
    public IActionResult Index() => View(_service.GetAllPublished());

    [HttpGet]
    public async Task<IActionResult> Editor(Guid? id) => View(await _service.GetByIdAsync(id));
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Editor(PostCategoryDto model)
    {
        var result = _service.Save(model, ModelState);
        if (result.Success)
            return RedirectToAction(nameof(Index));

        SetAlert(result);
        return View(model);
    }
    [HttpPost]
    public async Task<IActionResult> Delete(Guid id) => Ok(await _service.DeleteAsync(id));

    [HttpGet]
    public IActionResult Approvals() => View();
    [HttpGet]
    public IActionResult History(Guid id) => PartialView("_History", _service.HistoryVersions(id));
    [HttpGet]
    public IActionResult HistoryDetails(Guid id) => PartialView("_HistoryDetails", _service.HistoryDetails(id));
    [HttpPost]
    public IActionResult ConfirmPublish(Guid id) => Ok(_service.ConfirmPublish(id));
    [HttpPost]
    public IActionResult CancelPublish(Guid id) => Ok(_service.CancelPublish(id));
    [HttpPost]
    public IActionResult ConfirmDelete(Guid id) => Ok(_service.ConfirmDelete(id));
    [HttpPost]
    public IActionResult CancelDelete(Guid id) => Ok(_service.CancelDelete(id));
    [HttpPost]
    public IActionResult PublishAll() => Ok(_service.PublishAll());
    [HttpPost]
    public IActionResult DeleteAll() => Ok(_service.DeleteAll());
    [HttpPost]
    public IActionResult CancelDeleteAll() => Ok(_service.CancelDeleteAll());
    [HttpPost]
    public IActionResult CancelPublishAll() => Ok(_service.CancelPublishAll());
    [HttpPost]
    public async Task<IActionResult> Resort(Guid[] ids) => Ok(await _service.ResortAsync(ids));
    [HttpPost]
    public IActionResult PublishRequestCount() => Ok(_service.GetPublishAndDeleteRequestCount());
}

Thmanyah.CMS/Controllers/PostsController.cs
using Application.Controllers;
using Application.Services.Contracts;
using Domain.Dtos;
using Infrastructure.Providers.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace Thmanyah.CMS.Controllers;
public class PostsController : BaseAdminController
{
    private readonly IPostService _service;
    private readonly IFileProvider _fileProvider;
    public PostsController(IPostService service, IFileProvider fileProvider)
    {
        _service = service;
        _fileProvider = fileProvider;
    }
    [HttpGet]
    public IActionResult Index() => View(_service.GetAllPublished());

    [HttpGet]
    public async Task<IActionResult> Editor(Guid? id) => View(await _service.GetByIdAsync(id));
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Editor(PostDto model, IFormFile? imageFile)
    {
        if (imageFile != null)
        {
            string? imagePath = await _fileProvider.UploadFile(imageFile);
            if (!string.IsNullOrEmpty(imagePath))
            {
                model.Image = imagePath;
                ModelState.Remove("Image");
            }
        }
        var result = _service.Save(model, ModelState);
        if (result.Success)
            return RedirectToAction(nameof(Index));

        SetAlert(result);
        return View(model);
    }
    [HttpPost]
    public async Task<IActionResult> Delete(Guid id) => Ok(await _service.DeleteAsync(id));

    [HttpGet]
    public IActionResult Approvals() => View();
    [HttpGet]
    public IActionResult History(Guid id) => PartialView("_History", _service.HistoryVersions(id));
    [HttpGet]
    public IActionResult HistoryDetails(Guid id) => PartialView("_HistoryDetails", _service.HistoryDetails(id));
    [HttpPost]
    public IActionResult ConfirmPublish(Guid id) => Ok(_service.ConfirmPublish(id));
    [HttpPost]
    public IActionResult CancelPublish(Guid id) => Ok(_service.CancelPublish(id));
    [HttpPost]
    public IActionResult ConfirmDelete(Guid id) => Ok(_service.ConfirmDelete(id));
    [HttpPost]
    public IActionResult CancelDelete(Guid id) => Ok(_service.CancelDelete(id));
    [HttpPost]
    public IActionResult PublishAll() => Ok(_service.PublishAll());
    [HttpPost]
    public IActionResult DeleteAll() => Ok(_service.DeleteAll());
    [HttpPost]
    public IActionResult CancelDeleteAll() => Ok(_service.CancelDeleteAll());
    [HttpPost]
    public IActionResult CancelPublishAll() => Ok(_service.CancelPublishAll());
    [HttpPost]
    public async Task<IActionResult> Resort(Guid[] ids) => Ok(await _service.ResortAsync(ids));
    [HttpPost]
    public IActionResult PublishRequestCount() => Ok(_service.GetPublishAndDeleteRequestCount());
}

Thmanyah.CMS/Controllers/RolesController.cs
using Application.Controllers;
using Application.Services.Contracts;
using Domain.Dtos;
using Microsoft.AspNetCore.Mvc;

namespace Thmanyah.CMS.Controllers;
public class RolesController : BaseAdminController
{
    private readonly IRoleService _service;
    public RolesController(IRoleService service) => _service = service;
    public async Task<IActionResult> Index() => View(await _service.GetAllAsync());
    [HttpGet]
    public async Task<IActionResult> Editor(string? id) => View("Editor", await _service.GetByIdAsync(id));
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Editor(RoleDto model)
    {
        var result = await _service.SaveAsync(model, ModelState);
        if (result.Success)
            return RedirectToAction(nameof(Index));

        SetAlert(result);
        return View(model);
    }
    [HttpPost]
    public async Task<IActionResult> Delete(string id) => Ok(await _service.DeleteAsync(id));


}

Thmanyah.CMS/Controllers/UsersController.cs
using Application.Controllers;
using Application.Services.Contracts;
using Domain.Dtos;
using Microsoft.AspNetCore.Mvc;

namespace Thmanyah.CMS.Controllers;
public class UsersController : BaseAdminController
{
    private readonly IUserService _service;
    public UsersController(IUserService service) => _service = service;
    [HttpGet]
    public async Task<IActionResult> Index() => View(await _service.GetAllAsync());

    [HttpGet]
    public IActionResult Editor(string? id) => View(_service.GetUserById(id ?? string.Empty));
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Editor(UserDto model)
    {
        var result = await _service.SaveAsync(model, ModelState);
        if (result.Success)
            return RedirectToAction(nameof(Index));

        SetAlert(result);
        return View(model);
    }
    [HttpPost]
    public async Task<IActionResult> Delete(string id) => Ok(await _service.DeleteAsync(id));
}

Thmanyah.CMS/Views/Shared/_ApprovalsLayout.cshtml
@{
    Layout = "_Layout";
    ViewData["HasBreadcrumb"] = true;
}
@* @section breadcrumb {
    <ol class="breadcrumb fs-5 fw-semibold">
        <li class="breadcrumb-item"><a href="/" class="fw-bold"><i class="ki-duotone ki-home fs-4"></i> @Resources.HomePage</a></li>
        <li><i class="ki-duotone ki-right mx-1"><span class="path1"></span><span class="path2"></span></i></li>
        <li class="breadcrumb-item"><a href="/@_sessionProvider.CurrentControllerName/" class="fw-bold">@ViewData["Title"]</a></li>
        <li><i class="ki-duotone ki-right mx-1"><span class="path1"></span><span class="path2"></span></i></li>
        <li class="breadcrumb-item">@Resources.ApprovalsPage</li>
    </ol>
}
 *@

@RenderBody()

Thmanyah.CMS/Views/Shared/_History.cshtml
@model List<EntityHistoryViewModel>
@if(Model != null){
    <table class="table table-striped">
        <thead>
            <tr>
                <th>@Resources.Name</th>
                <th>@Resources.Status</th>
                <th>@Resources.Date</th>
                <th>@Resources.Time</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.OrderByDescending(o => o.CreatedAt))
            {
                var user = _userService.GetUserById(item.CreatedBy?.ToString() ?? string.Empty);
                string userName = user != null ? (!string.IsNullOrEmpty(user.Name) ? user.Name : "Administrator") : "Administrator";
                <tr>
                    <td>@userName</td>
                    <td>
                        @if (item.IsNeedDeleteApprove)
                        {
                            <span class="badge badge-danger">@Resources.PendingToDelete</span>
                        }
                        else
                        {
                            if (!item.IsPublished ?? false)
                            {
                                <span class="badge badge-info">@Resources.PendingToUpdate</span>
                            }
                            else
                            {
                                <span class="badge badge-success">@Resources.Published</span>
                            }
                        }
                    </td>
                    <td>@item.CreatedAt?.ToString("dd-MM-yyyy")</td>
                    <td>@item.CreatedAt?.ToString("HH:mm:ss tt")</td>
                    <td></td>
                </tr>
            }
        </tbody>
    </table>
}else{
    <div class="alert alert-warning w-100 p-5 mb-10">
        <div class="d-flex flex-column flex-sm-row">
            <i class="ki-duotone ki-notification-bing fs-2hx me-4 mb-5 mb-sm-0 text-warning"><span class="path1"></span><span class="path2"></span><span class="path3"></span></i>
            <div class="d-flex flex-column pe-0 pe-sm-10 text-warning">
                <span>@Resources.NoRecordsFound</span>
            </div>
        </div>
    </div>
}

Thmanyah.CMS/Views/Shared/_HistoryDetails.cshtml
@model EntityHistoryDetailsViewModel
@{
    var current = Model.Current;
    var version = Model.Version;
    var properties = current.GetType().GetProperties();
    var dtoProperties = typeof(BaseDto).GetProperties();
}

@if(version != null)
{
   <div class="container-history">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>@Resources.TheField</th>
                    <th>@Resources.Value</th>
                 @*   <th>@Resources.IsDifferent</th>*@
                </tr>
            </thead>
            <tbody>
                @foreach (var prop in properties)
                {
                    if (!dtoProperties.Any(a => a.Name == prop.Name))
                    {
                        string propertyValue = string.Empty;
                        string propertyName = Resources.ResourceManager.GetString(prop.Name) ?? prop.Name;
                        Type propertyType = prop.PropertyType;

                        var currentValue = string.Empty;
                        var versionValue = string.Empty;
                        if (propertyType == typeof(List<MultilingualField>))
                        {
                            // Multilingual Text
                            var currentMultilingual = (List<MultilingualField>?)prop.GetValue(current) ?? new List<MultilingualField>();
                            var versionMultilingual = (List<MultilingualField>?)prop.GetValue(version) ?? new List<MultilingualField>();
                            if (currentMultilingual != null)
                                foreach (var item in currentMultilingual.Select((value, i) => new { i, value }))
                                    currentValue += $"{(item.i != 0 ? "<br>" : string.Empty)} {item.value.Value?.ToString()}";

                            if (versionMultilingual != null)
                                foreach (var item in versionMultilingual.Select((value, i) => new { i, value }))
                                    versionValue += $"{(item.i != 0 ? "<br>" : string.Empty)} {item.value.Value?.ToString()}";

                            propertyValue = _htmlProvider.Difference(currentValue, versionValue);
                        }
                        else if (propertyType == typeof(Guid) || propertyType == typeof(Guid?))
                        {
                            if (!prop.Name.EndsWith("Id"))
                            {
                                @* var file = _mediaFileService.GetFileTypeById(Guid.Parse(prop.GetValue(current)?.ToString() ?? Guid.Empty.ToString()));
                                if (file == MediaFileType.Image)
                                {
                                    // Display image thumbnail
                                    currentValue = _mediaFileService.GetImageThumbnailById(Guid.Parse(prop.GetValue(current)?.ToString() ?? Guid.Empty.ToString()));
                                    versionValue = _mediaFileService.GetImageThumbnailById(Guid.Parse(prop.GetValue(version)?.ToString() ?? Guid.Empty.ToString()));
                                    propertyValue = $"<img src='{currentValue}' class='mx-2 border border-4 border-secondary rounded sbc-height-50' />{(currentValue != versionValue ? $"<img src='{versionValue}' class='mx-2 border border-4 border-warning rounded sbc-height-50' />" : string.Empty)}";
                                }
                                else
                                {
                                    currentValue = _mediaFileService.GetFilePathById(Guid.Parse(prop.GetValue(current)?.ToString() ?? Guid.Empty.ToString()));
                                    versionValue = _mediaFileService.GetFilePathById(Guid.Parse(prop.GetValue(version)?.ToString() ?? Guid.Empty.ToString()));
                                    if (file == MediaFileType.Video)
                                    {
                                        // Display video preview
                                        propertyValue = $"<video class='mx-2 border border-4 border-secondary rounded sbc-height-150' controls><source src='{currentValue}' type='video/mp4'></video>" +
                                        $"{(currentValue != versionValue ? $"<video class='mx-2 border border-4 border-warning rounded sbc-height-150' controls><source src='{versionValue}' type='video/mp4'></video>" : string.Empty)}";
                                    }
                                    else
                                    {
                                        // Handle other file types
                                        propertyValue = $"<a href='{currentValue}' ><img src='/assets/media/files/file.png' class='border border-4 border-secondary rounded sbc-defult-file'></a>" +
                                        $"{(currentValue != versionValue ? $"<a href='{versionValue}'><img src='/assets/media/files/file.png' class='border border-4 border-warning rounded sbc-defult-file'></a>" : string.Empty)}";
                                    }
                                }
 *@
                            }
                            else
                            {
                                //Ids F.K.
                                var interfaceType = Type.GetType($"Application.Services.Contracts.I{prop.Name.Replace("Id", string.Empty)}Service, Application");
                                if (interfaceType != null)
                                {
                                    try
                                    {
                                        var type = interfaceType.GetInterfaces().FirstOrDefault();
                                        if (type != null)
                                        {
                                            var service = _serviceProvider.GetService(type) as dynamic;
                                            if (service != null)
                                            {
                                                string currentName = service.GetName(Guid.Parse(prop.GetValue(current)?.ToString() ?? Guid.Empty.ToString()));
                                                string versionName = service.GetName(Guid.Parse(prop.GetValue(current)?.ToString() ?? Guid.Empty.ToString()));
                                                propertyValue = _htmlProvider.Difference(currentName, versionName);
                                            }
                                        }    
                                    }
                                    catch { }
                                }
                            }
                        }
                        else if (propertyType == typeof(bool) || propertyType == typeof(bool?))
                        {
                            // Logic
                            currentValue = bool.Parse(prop.GetValue(current)?.ToString() ?? "False") ? Resources.Yes : Resources.No;
                            versionValue = bool.Parse(prop.GetValue(version)?.ToString() ?? "False") ? Resources.Yes : Resources.No;
                            propertyValue = $"<span class='badge badge-secondary'>{currentValue}</span> {(currentValue != versionValue ? "<span class='badge badge-success'>" + versionValue + "</span>" : string.Empty)}";
                        }
                        else if (propertyType == typeof(DateTime) || propertyType == typeof(DateTime?))
                        {
                            // Date Time
                            currentValue = prop.GetValue(current)?.ToString() ?? string.Empty;
                            versionValue = prop.GetValue(version)?.ToString() ?? string.Empty;
                            propertyValue = $"<span class='badge badge-secondary'>{currentValue}</span> {(currentValue != versionValue ? "<span class='badge badge-success'>" + versionValue + "</span>" : string.Empty)}";
                        }
                        else if(propertyType == typeof(string))
                        {
                            currentValue = prop.GetValue(current)?.ToString() ?? string.Empty;
                            versionValue = prop.GetValue(version)?.ToString() ?? string.Empty;

                            if (currentValue.Contains("{\"value\":\""))
                                currentValue = currentValue.TagifyToString();

                            if (versionValue.Contains("{\"value\":\""))
                                versionValue = versionValue.TagifyToString();

                            propertyValue = !string.IsNullOrEmpty(versionValue) ? _htmlProvider.Difference(currentValue, versionValue) : string.Empty;

                           

                        }
                        else
                        {
                            continue;
                        }
                        bool isDifferent = currentValue != versionValue;
                        if (isDifferent)
                        {
                            <tr>
                                <td>@propertyName</td>
                                <td>
                                    @Html.Raw(propertyValue)
                                </td>
                                @*<td>
                                    @if (isDifferent)
                                    {
                                        <span class="badge bad badge-success">@Resources.Yes</span>
                                    }
                                    else
                                    {
                                        <span class="badge bad badge-secondary">@Resources.No</span>
                                    }
                                </td>*@
                            </tr>
                        }          
                    }
                }
            </tbody>
        </table>
   </div>
}
else
{
    <partial name="Partials/_NoDataFound" />
}

Thmanyah.CMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Resources.SiteName</title>
    @* <link rel="stylesheet" href="/assets/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="/assets/plugins/select2/css/select2.min.css" rel="stylesheet" />
<link href="/assets/plugins/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
<link href="/assets/plugins/summernote/summernote-lite.min.css" rel="stylesheet" />
    
    <link rel="stylesheet" href="/assets/css/style.css" asp-append-version="true" />
@*     <link rel="stylesheet" href="/assets/Thmanyah.CMS.styles.css" asp-append-version="true" /> *@
    <link rel="shortcut icon" href="/assets/images/favicon.ico" />
</head>
<body>

    <input type="hidden" id="hdn-locale" name="hdn-locale" value="@_sessionProvider.GetCurrentLocale()" />

    <input type="hidden" id="hdn-action-confirm" value="@Resources.ActionConfirm" />
    <input type="hidden" id="hdn-action-delete-message" value="@Resources.ActionDeleteMessage" />
    <input type="hidden" id="hdn-action-publish-message" value="@Resources.ActionPublishMessage" />
    <input type="hidden" id="hdn-action-cancel-changes-message" value="@Resources.ActionCancelChangesMessage" />
    <input type="hidden" id="hdn-action-confirm-delete-message" value="@Resources.ActionConfirmDeleteMessage" />
    <input type="hidden" id="hdn-action-publish-all-message" value="@Resources.ActionPublishAllMessage" />
    <input type="hidden" id="hdn-action-create-copy-message" value="@Resources.ActionCreateCopyMessage" />
    <input type="hidden" id="hdn-action-yes" value="@Resources.Yes" />
    <input type="hidden" id="hdn-action-no" value="@Resources.No" />
    <input type="hidden" id="hdn-action-ok" value="@Resources.Ok" />
    <input type="hidden" id="hdn-action-cancel" value="@Resources.Cancel" />
    <input type="hidden" id="hdn-action-confirm" value="@Resources.Confirm" />

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="/assets/images/logo-black.png"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    @if (_sessionProvider.IsLoggedInUser())
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark fw-bold" asp-controller="Home" asp-action="Index">الرئيسية</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark fw-bold" asp-controller="Categories" asp-action="Index">التصنيفات</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark fw-bold" asp-controller="Posts" asp-action="Index">المقالات</a>
                            </li>

                            @if (_sessionProvider.HasPermission(PermissionKey.FullControl))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark fw-bold" asp-controller="Users" asp-action="Index">المستخدمين</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark fw-bold" asp-controller="Roles" asp-action="Index">الصلاحيات</a>
                                </li>
                            }
                         
                        </ul>

                        <div class="dropdown">
  <button class="btn d-flex align-items-center gap-2 p-0 border-0 bg-transparent" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
 
    <!-- Avatar -->
    <div class="rounded-circle bg-dark text-white d-flex align-items-center justify-content-center" style="width: 40px; height: 40px;">
      <span class="fw-bold">MK</span>
    </div>
      <!-- Label -->
    <span class="fw-semibold">مرحبا، @_sessionProvider.GetLoggedInUserInfo()?.Name</span>

  </button>
  <ul class="dropdown-menu dropdown-menu-end mt-2" aria-labelledby="userDropdown">
@*     <li><a class="dropdown-item" href="#">الصفحة الشخصية</a></li>
    <li><a class="dropdown-item" href="#">الإعدادات</a></li>
    <li><hr class="dropdown-divider"></li> *@
    <li><a class="dropdown-item text-danger" href="/auth/logout"><i class="fa fa-sign-out"></i> تسجيل خروج</a></li>
  </ul>
</div>


                     @*    <a class="btn btn-sm btn-dark" asp-action="logout" asp-controller="auth">تسجيل الخروج</a> *@
                    }
                    else
                    {
                        <a class="btn btn-sm btn-dark"  asp-action="login" asp-controller="auth">تسجيل الدخول</a>

                    }

                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year - @Resources.SiteName
        </div>
    </footer>
       <partial name="Partials/_MainModal" />
    <script src="/assets/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/js/all.min.js" integrity="sha512-b+nQTCdtTBIRIbraqNEwsjB6UvL3UEMkXnhzd8awtCYh0Kcsjl9uEgwVFVbhoj3uu1DO1ZMacNvLoyJJiNfcvg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
   <script src="/assets/plugins/select2/js/select2.full.min.js" asp-append-version="true"></script>
    <script src="/assets/plugins/sweetalert2/sweetalert2.all.min.js" asp-append-version="true"></script>
    <script src="/assets/plugins/summernote/summernote-lite.min.js" asp-append-version="true"></script>
    
    @* <script src="/assets/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script type="module" src="/assets/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>